# Lineare Algebra für Data Science und absolute Beginner (II/II)
![beginner](https://upload.wikimedia.org/wikipedia/commons/f/f7/ABSOLUTE_BEGINNER.jpg "Von Mika Väisänen, CC BY-SA 3.0 de, https://commons.wikimedia.org/w/index.php?curid=38500036")

In [2]:
# numpy als eine Implementierung von LA
import numpy as np
from numpy import linalg as LA
# pandas zum Vergleich zur LA
import pandas as pd
# pyplot, um Grafiken anzuzeigen
import matplotlib.pyplot as plt

import sympy as sp
from sympy import Matrix, init_printing
init_printing()

In [7]:
display(sp.sqrt(8))

In [23]:
A = np.array([[1,2,3],
              [4,5,6]])

V1 = np.array([1,2,3])

print(A@V1)
# print(V1@A)


[14 32]


# Ideen
1. Eigenvektoren // google Page Rank
2. Sonderfall Identitätsmatrix
3. Verstehen, was eine Matrix tut > mit Matrix experimentieren
4. PErmutationsmatrix >> Zeilen und Spalten vertauschen
5. Inverse Matrix >> Sachen rückgängig machen.
6. Determinanten
8. Projektionsmatrizen / REgression als Matrixmultiplikation

MAtrixMultiplikation: Alles hängt irgendwie zusammen

MArkovmatrix

Graphentheorie

page rank

SVD

PCA

Sparse

S LAMBDA S-1 -Transformation

# Matrixmultiplikation besser verstehen

In [24]:
A =    np.array([[1,2,3],
                 [4,5,11],
                 [7,8,12]])

In [25]:
I = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])

In [26]:
V = np.array([1,2,3])

In [31]:
# Strg-Z
neuesI = A @ LA.inv(A)
display(Matrix(np.round(neuesI, decimals=2)))

# print(np.around(A @ LA.inv(A), decimals=2))

⎡1.0   0    0 ⎤
⎢             ⎥
⎢ 0   1.0   0 ⎥
⎢             ⎥
⎣ 0    0   1.0⎦

In [34]:
A_projection = A @ LA.inv(A.T @ A) @ A.T
print(display(Matrix(np.round(A_projection))))

⎡1.0   0    0 ⎤
⎢             ⎥
⎢ 0   1.0   0 ⎥
⎢             ⎥
⎣ 0    0   1.0⎦

None


In [ ]:




 I@A

array([[ 1,  2,  3],
       [ 4,  5, 11],
       [ 7,  8, 12]])

In [ ]:
A*I

array([[ 1,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 12]])

In [ ]:
B = np.matrix([[0,0,1],
               [1,0,0],
               [0,1,0]])

print(B)

[[0 0 1]
 [1 0 0]
 [0 1 0]]


In [ ]:
# row swap 
# row operations = left multiplication of B with A
# B means: write row 3 in row 1
B*A

matrix([[ 7,  8, 12],
        [ 1,  2,  3],
        [ 4,  5, 11]])

In [ ]:
# col swap 
# col operations = left multiplication of B with A
# B means: write col 3 in col 1
A*B

matrix([[ 2,  3,  1],
        [ 5, 11,  4],
        [ 8, 12,  7]])

In [ ]:
# C
C = I.copy()
C[1,0] = -1
C

array([[ 1,  0,  0],
       [-1,  1,  0],
       [ 0,  0,  1]])

In [ ]:
AT = A.transpose()

In [ ]:
AT

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3, 11, 12]])

In [ ]:
A*AT

array([[  1,   8,  21],
       [  8,  25,  88],
       [ 21,  88, 144]])

In [ ]:
AT*A

array([[  1,   8,  21],
       [  8,  25,  88],
       [ 21,  88, 144]])

In [ ]:
# SAS-Transformation

eigvals_staub
S = eigvectors_staub
SI = LA.inv(eigvectors_staub)

I = np.array([[1,0],
              [0,1]])

LAMBDA = eigvals_staub * I
LAMBDA2 = LAMBDA @ LAMBDA

S @ LAMBDA @ SI


array([[0.66, 0.32],
       [0.16, 0.66]])

array([[0.66, 0.32],
       [0.16, 0.66]])

In [ ]:
LAMBDA

array([[0.94142136, 0.        ],
       [0.        , 0.65857864]])

In [ ]:

%%timeit
S @ LAMBDA2 @ SI


3.45 µs ± 453 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%%timeit
zombifizierungmatrix_staub @ zombifizierungmatrix_staub

2.09 µs ± 296 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
