# Matrixmultiplikation besser verstehen

# Ideen
1. Eigenvektoren // google Page Rank
2. Sonderfall Identitätsmatrix
3. Verstehen, was eine Matrix tut > mit Matrix experimentieren
4. PErmutationsmatrix >> Zeilen und Spalten vertauschen
5. Inverse Matrix >> Sachen rückgängig machen.
6. Determinanten
8. Projektionsmatrizen / REgression als Matrixmultiplikation

MAtrixMultiplikation: Alles hängt irgendwie zusammen

Graphentheorie

page rank

SVD

PCA

Sparse

S LAMBDA S-1 -Transformation

In [ ]:
A =    np.array([[1,2,3],
                 [4,5,11],
                 [7,8,12]])

In [ ]:
I = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])

In [ ]:
V = np.array([1,2,3])

In [ ]:
print(A @ LA.inv(A))

[[ 1.00000000e+00  0.00000000e+00 -2.77555756e-17]
 [ 3.33066907e-16  1.00000000e+00  1.38777878e-16]
 [ 4.44089210e-16  0.00000000e+00  1.00000000e+00]]


In [ ]:
A_projection = A @ LA.inv(A.T @ A) @ A.T
print(A_projection)

[[ 1.00000000e+00  4.38538095e-15 -1.99840144e-15]
 [ 4.71844785e-15  1.00000000e+00  4.21884749e-15]
 [-4.71844785e-15 -2.38697950e-15  1.00000000e+00]]


In [ ]:




 I@A

array([[ 1,  2,  3],
       [ 4,  5, 11],
       [ 7,  8, 12]])

In [ ]:
A*I

array([[ 1,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 12]])

In [ ]:
B = np.matrix([[0,0,1],
               [1,0,0],
               [0,1,0]])

print(B)

[[0 0 1]
 [1 0 0]
 [0 1 0]]


In [ ]:
# row swap 
# row operations = left multiplication of B with A
# B means: write row 3 in row 1
B*A

matrix([[ 7,  8, 12],
        [ 1,  2,  3],
        [ 4,  5, 11]])

In [ ]:
# col swap 
# col operations = left multiplication of B with A
# B means: write col 3 in col 1
A*B

matrix([[ 2,  3,  1],
        [ 5, 11,  4],
        [ 8, 12,  7]])

In [ ]:
# C
C = I.copy()
C[1,0] = -1
C

array([[ 1,  0,  0],
       [-1,  1,  0],
       [ 0,  0,  1]])

In [ ]:
AT = A.transpose()

In [ ]:
AT

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3, 11, 12]])

In [ ]:
A*AT

array([[  1,   8,  21],
       [  8,  25,  88],
       [ 21,  88, 144]])

In [ ]:
AT*A

array([[  1,   8,  21],
       [  8,  25,  88],
       [ 21,  88, 144]])

In [ ]:
# SAS-Transformation

eigvals_staub
S = eigvectors_staub
SI = LA.inv(eigvectors_staub)

I = np.array([[1,0],
              [0,1]])

LAMBDA = eigvals_staub * I
LAMBDA2 = LAMBDA @ LAMBDA

S @ LAMBDA @ SI


array([[0.66, 0.32],
       [0.16, 0.66]])

array([[0.66, 0.32],
       [0.16, 0.66]])

In [ ]:
LAMBDA

array([[0.94142136, 0.        ],
       [0.        , 0.65857864]])

In [ ]:

%%timeit
S @ LAMBDA2 @ SI


3.45 µs ± 453 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
%%timeit
zombifizierungmatrix_staub @ zombifizierungmatrix_staub

2.09 µs ± 296 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
