# Linear algebra for data science and absolute beginners (II/II)
![beginner](https://upload.wikimedia.org/wikipedia/commons/f/f7/ABSOLUTE_BEGINNER.jpg "By Mika Väisänen, CC BY-SA 3.0 en, https://commons.wikimedia.org/w/index.php?curid=38500036")



In [2]:
import numpy as np



# Understand matrix multiplication better

Hi and nice to have you back.

After our introductory example, let's take a look at exactly how matrix multiplication works (part 1) and what you can do with it (part 2). To do this, let's first try to get some intuition. Imagine you have two matrices $A$ and $B$: 




In [3]:

A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A+B)


[[ 6  8]
 [10 12]]


What happens if we add or subtract these two matrices?

In [4]:

print("A+B")
print(A+B)
print("A-B")
print(A-B)


A+B
[[ 6  8]
 [10 12]]
A-B
[[-4 -4]
 [-4 -4]]


You can see that the sum of the two matrices $A$ and $B$ is the sum of the individual elements (or the difference). This is not particularly exciting. What happens if we multiply the two matrices together? Now the only question is: In which order? Never mind, let's take both!

In [5]:

print("A*B")
print(A@B)
print("B*A")
print(B@A)


A*B
[[19 22]
 [43 50]]
B*A
[[23 34]
 [31 46]]


First observation: The order does matter! Matrix multiplication is not commutative. This means that $A \cdot B \neq B \cdot A$. 

Now let's take a few other matrix sizes and see what happens. 


In [6]:

A = np.array([[6,3],
              [2,2],
              [1,6],
              [8,6]])

B = np.array([[8,0,0],
              [9,5,0]])


In [7]:

print("A*B")
print(A@B)


A*B
[[ 75  15   0]
 [ 34  10   0]
 [ 62  30   0]
 [118  30   0]]



    

Very nice, that seems to work. But what happens if we swap the matrices?



In [8]:

print("B*A")
print(B@A)


B*A


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)



Now we get an error message! This means that the matrix multiplication cannot be carried out in this way. The error message says: "size 4 is different from 3". This means that the number of columns in the first matrix must be equal to the number of rows in the second matrix. But why? Let's take a closer look. The following graphic shows the matrix multiplication of $A$ and $B$:

![Matrix multiplication](https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/1920px-Matrix_multiplication_diagram_2.svg.png "By Inductiveload - Own work, CC BY-SA 3.0, https://commons.wikimedia.org/w/index.php?curid=1119724")

If you arrange the matrices $A$ and $B$ as shown in the graphic above, it becomes clear that the number of columns in the first matrix must be equal to the number of rows in the second matrix. To determine the value in the red circle, for example, I have to calculate the following:

$(a_{1,1}*b_{1,2})+ (a_{1,2}*b_{2,2})$

To do this, the columns of $A$ and the rows of $B$ must be the same. The rows of $A$ and the columns of $B$ are different. These can be of any length. Therefore, the matrix multiplication also has the form $m \times n$ and $n \times p$. The result is then a matrix of size $m \times p$. So $n$ no longer appears in the result matrix. This will be very useful for us when we deal with dimension reduction or language models such as GPT, for example.

So far so good! Now let's take a look at a few special cases of matrices. First the unit matrix, also called identity $I$. This has only ones on the main diagonal and otherwise only zeros. Now we multiply the matrix $A$ by the unit matrix $I$ to see what happens to $A$.




In [9]:

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

I = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])

# Shortcut: I = np.eye(3)

print("A*I")
print(A@I)
print("I*A")
print(I@A)


A*I
[[1 2 3]
 [4 5 6]
 [7 8 9]]
I*A
[[1 2 3]
 [4 5 6]
 [7 8 9]]



    

Interesting! The matrix $A$ remains the same. This means that the unit matrix $I$ is the so-called "neutral element" of the matrix multiplication. This is similar to the number 1 in the multiplication of "numbers". But why is this the case?

Let's take a look at the first digit in the result matrix. This is the sum of the products of the first row of $A$ with the first column of $I$. This means that we multiply the first row of $A$ by the first column of $I$. In this case, that is:

Digit "1": $1*1 + 2*0 + 3*0 = 1$

Digit "2": $1*0 + 2*1 + 3*0 = 2$

Digit "4": $4*1 + 5*0 + 6*0 = 4$

etc.

What happens now if we manipulate $I$ a little?




In [10]:

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[0,1,0],
              [1,0,0],
              [0,0,1]])

print("A*B")
print(A@B)


A*B
[[2 1 3]
 [5 4 6]
 [8 7 9]]




Now the first two columns are swapped! You can also read the matrix $B$ like this: 

If there is a "1" in the __first__ column in the __second__ place, this means: 

"Take the __first__ column of $A$ and write it in the __second__ column." 

If there is a "1" in the __second__ column in the __first__ place, this means: 

"Take the __second__ column of $A$ and write it in the __first__ column." 

So I can swap columns with a matrix multiplication! But what about rows? Do you have any ideas? We can simply swap the order of the matrices and see what happens.



In [11]:
print("B*A")
print(B@A)

B*A
[[4 5 6]
 [1 2 3]
 [7 8 9]]



    

Zack! And now we have swapped rows. We can now read the matrix $B$ as follows:

If there is a "1" in the __first__ row in the __second__ place, this means: 

"Take the __first__ row of $A$ and write it in the __second__ row." 

If there is a "1" in the __second__ line in the __first__ place, this means: 

"Take the __second__ line of $A$ and write it on the __first__ line." 

Now let's continue in a different way. We now build a so-called lower triangular matrix $L$ of ones. This has only ones on the main diagonal and also below it. Everything else is zero. Let's see what happens when we multiply $A$ by $L$.





In [12]:

L = np.array([[1,0,0],
              [1,1,0],
              [1,1,1]])

print("A*L")
print(A@L)

print("L*A")
print(L@A)

A*L
[[ 6  5  3]
 [15 11  6]
 [24 17  9]]
L*A
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [13]:

# numpy as an implementation of LA
import numpy as np
from numpy import linalg as LA
# pandas for comparison to LA
import pandas as pd
# pyplot to display graphics
import matplotlib.pyplot as plt

import sympy as sp
from sympy import Matrix, init_printing
init_printing()


In [14]:

display(sp.sqrt(8))


In [15]:
A = np.array([[1,2,3],
              [4,5,6]])

V1 = np.array([1,2,3])

print(A@V1)
# print(V1@A)

[14 32]



# Ideas
1. eigenvectors // google page rank
2. special case identity matrix
3. understand what a matrix does &gt; experiment with matrix
4. permutation matrix &gt;&gt; swap rows and columns
5. inverse matrix &gt;&gt; undo things.
6. determinants
8. projection matrices / REgression as matrix multiplication

MAtrix multiplication: Everything is somehow connected

MArkov matrix

Graph theory

page rank

SVD

PCA

Sparse

S LAMBDA S-1 transformation

# Understand matrix multiplication better


In [16]:

A = np.array([[1,2,3],
                 [4,5,11],
                 [7,8,12]])


In [17]:

I = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])


In [18]:

V = np.array([1,2,3])

In [19]:

# Ctrl-Z
newI = A @ LA.inv(A)
display(Matrix(np.round(newI, decimals=2)))

# print(np.around(A @ LA.inv(A), decimals=2))


⎡1.0  0.0  0.0⎤
⎢             ⎥
⎢0.0  1.0  0.0⎥
⎢             ⎥
⎣0.0  0.0  1.0⎦

In [20]:

A_projection = A @ LA.inv(A.T @ A) @ A.T
print(display(Matrix(np.round(A_projection))))


⎡1.0  0.0  0.0⎤
⎢             ⎥
⎢0.0  1.0  0.0⎥
⎢             ⎥
⎣0.0  0.0  1.0⎦

None


In [21]:

I@A


array([[ 1,  2,  3],
       [ 4,  5, 11],
       [ 7,  8, 12]])

In [22]:

A*I


array([[ 1,  0,  0],
       [ 0,  5,  0],
       [ 0,  0, 12]])

In [23]:

B = np.matrix([[0,0,1],
               [1,0,0],
               [0,1,0]])

print(B)


[[0 0 1]
 [1 0 0]
 [0 1 0]]


In [24]:

# row swap 
# row operations = left multiplication of B with A
# B means: write row 3 in row 1
B*A


matrix([[ 7,  8, 12],
        [ 1,  2,  3],
        [ 4,  5, 11]])

In [25]:

# col swap 
# col operations = left multiplication of B with A
# B means: write col 3 in col 1
A*B


matrix([[ 2,  3,  1],
        [ 5, 11,  4],
        [ 8, 12,  7]])

In [26]:

# C
C = I.copy()
C[1,0] = -1
C


array([[ 1,  0,  0],
       [-1,  1,  0],
       [ 0,  0,  1]])

In [27]:

AT = A.transpose()


In [28]:

AT


array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3, 11, 12]])

In [29]:

A*AT


array([[  1,   8,  21],
       [  8,  25,  88],
       [ 21,  88, 144]])

In [30]:

AT*A




array([[  1,   8,  21],
       [  8,  25,  88],
       [ 21,  88, 144]])

In [31]:

# SAS transformation

eigvals_dust
S = eigvectors_dust
SI = LA.inv(eigvectors_dust)

I = np.array([[1,0],
              [0,1]])

LAMBDA = eigvectors_dust * I
LAMBDA2 = LAMBDA @ LAMBDA

S @ LAMBDA @ SI



NameError: name 'eigvals_dust' is not defined

In [ ]:
LAMBDA


In [ ]:
%%timeit
S @ LAMBDA2 @ SI

In [ ]:
%%timeit
zombificationmatrix_dust @ zombificationmatrix_dust

In [ ]:
A = np.array([ [1,2,3],
                [2,4,6],
                [3,4,0]])

In [ ]:

print(A)
A_norm_1 = LA.norm(A, axis=1, keepdims=True)
A_norm_0 = LA.norm(A, axis=0, keepdims=True)
print(A_norm_1**2)
print(A_norm_0)
print(((A @ A.T) / (A_norm_1**2))**2)



In [ ]:
A = np.array([ [1,0],
                [1,1],
                [1,2],
                [0,2]])

# LA.det(A)

In [ ]:
origin = np.zeros_like(A.T)
print(*origin)
plt.quiver(*origin, A[:,0], A[:,1], scale=7)
plt.show()


In [ ]:
(A@A.T) 

In [ ]:
LA.norm(A, axis=1, keepdims=True)@LA.norm(A, axis=0, keepdims=True)